# Generated by Django 5.2 on 2025-05-13 19:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_id', models.CharField(max_length=100)),
                ('from_me', models.BooleanField()),
                ('mensagem', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField()),
                ('has_media', models.BooleanField(default=False)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('media_tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('media_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='midias/')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
            },
        ),
    ]
