# Generated by Django 5.2 on 2025-05-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='anexos/'),
        ),
    ]
